/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clase4;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mjara
 */
public class Tablas extends javax.swing.JFrame {
    
    AccesoPerros perro = new AccesoPerros();
    DefaultTableModel tm;
    int fila;
    
    /**
     * Creates new form Tablas
     */
    public Tablas() {
        initComponents();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupSexo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtIdentificador = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPerritos = new javax.swing.JTable();
        cmbRaza = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        rdbMacho = new javax.swing.JRadioButton();
        rdbHembra = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        chbOperado = new javax.swing.JCheckBox();
        chbChip = new javax.swing.JCheckBox();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("id");

        jLabel2.setText("nombre");

        jLabel3.setText("edad");

        jLabel4.setText("raza");

        btnGuardar.setText("guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        tblPerritos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Edad", "Raza", "Sexo", "Operado", "Chip"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPerritos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPerritosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPerritos);

        cmbRaza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "labrador", "pug", "corgi", "terrier", "bulldog", "german sheperd", "dogo" }));
        cmbRaza.setSelectedIndex(-1);

        jLabel5.setText("Sexo");

        btnGroupSexo.add(rdbMacho);
        rdbMacho.setSelected(true);
        rdbMacho.setText("Macho");

        btnGroupSexo.add(rdbHembra);
        rdbHembra.setText("Hembra");

        jLabel6.setText("Otros");

        chbOperado.setText("Operado");

        chbChip.setText("chip");

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbRaza, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNombre))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuardar)
                            .addComponent(btnActualizar))
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(rdbMacho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbHembra)
                .addGap(42, 42, 42)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(chbOperado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chbChip)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(cmbRaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(rdbMacho)
                        .addComponent(rdbHembra))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(chbOperado)
                        .addComponent(chbChip)
                        .addComponent(btnEliminar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        int resp = JOptionPane.showConfirmDialog(tblPerritos, "¿seguro de ingresar perro?");
        if (resp == 0) {
            tm = (DefaultTableModel) tblPerritos.getModel();
        
        int id = Integer.parseInt(txtIdentificador.getText());
        String nom = txtNombre.getText();
        int ed = Integer.parseInt(txtEdad.getText());
        String raza = (String) cmbRaza.getSelectedItem();
        String sexo = comprobarSexo();
        boolean ope = chbOperado.isSelected();
        boolean chip = chbChip.isSelected();
        try {
            perro.ingresarPerros(id, nom, ed, raza, sexo, ope, chip);
            tm.addRow(new Object[]{id,nom,ed,raza,sexo,ope,chip});
            tblPerritos.setModel(tm);
            JOptionPane.showMessageDialog(null,"Ingresado con exito!","Ingreso perro", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
        }
        
        limpiar();
        }else{
            JOptionPane.showMessageDialog(null,"No ingresado!","Ingreso perro", JOptionPane.WARNING_MESSAGE);
        }
            
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tblPerritosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPerritosMouseClicked
        fila = tblPerritos.getSelectedRow();
        tm = (DefaultTableModel) tblPerritos.getModel();
        
        String id = String.valueOf(tm.getValueAt(fila, 0));
        txtIdentificador.setText(id);
        String nombre = String.valueOf(tm.getValueAt(fila, 1));
        txtNombre.setText(nombre);
        String edad = String.valueOf(tm.getValueAt(fila, 2));
        txtEdad.setText(edad);
        String raza = String.valueOf(tm.getValueAt(fila, 3));
        cmbRaza.setSelectedItem(raza);
        String sexo = String.valueOf(tm.getValueAt(fila, 4));
        instanciarSexo(sexo);
        boolean operado = (boolean) tm.getValueAt(fila, 5);
        chbOperado.setSelected(operado);
        boolean chip = (boolean) tm.getValueAt(fila, 6);
        chbChip.setSelected(chip);
        
    }//GEN-LAST:event_tblPerritosMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        
        tm = (DefaultTableModel) tblPerritos.getModel();
        
        int id = Integer.parseInt(txtIdentificador.getText());
        tm.setValueAt(id, fila, 0);
        String nombre = txtNombre.getText();
        tm.setValueAt(nombre, fila, 1);
        int edad = Integer.parseInt(txtEdad.getText());
        tm.setValueAt(edad, fila, 2);
        String raza = (String) cmbRaza.getSelectedItem();
        tm.setValueAt(raza, fila, 3);
        String sexo = comprobarSexo();
        tm.setValueAt(sexo, fila, 4);
        boolean ope = chbOperado.isSelected();
        tm.setValueAt(ope, fila, 5);
        boolean chip = chbChip.isSelected();
        tm.setValueAt(chip, fila, 6);
        
        perro.actualizarPerros(id, nombre, edad, raza, sexo, ope, chip);
        tblPerritos.setModel(tm);
        limpiar();
        
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        tm = (DefaultTableModel) tblPerritos.getModel();
        int id = (int) tm.getValueAt(fila, 0);
        perro.eliminarPerros(id);
        tm.removeRow(fila);
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablas().setVisible(true);
            }
        });
    }
    
    public void limpiar(){
        txtIdentificador.setText("");
        txtNombre.setText("");
        txtEdad.setText("");
        cmbRaza.setSelectedIndex(-1);
        chbOperado.setSelected(false);
        chbChip.setSelected(false);
        fila=-1;
    }
    
    public String comprobarSexo(){
        if (rdbMacho.isSelected()) {
            return "Macho";
        }else{
            return "hembra";
        }
    }
    
    public void instanciarSexo(String sexo){
        switch (sexo) {
            case "Macho":
                rdbMacho.setSelected(true);
            break;
            case "Hembra":
                rdbHembra.setSelected(true);
            break;
        }
    }
    
    public void cargarTabla(){
        ResultSet rs = perro.listarPerros();
        tm = (DefaultTableModel) tblPerritos.getModel();
        try {
            while (rs.next()) {
                int id = rs.getInt("id");
                String nombre = rs.getString("nombre");
                int edad = rs.getInt("edad");
                String raza = rs.getString("raza");
                String sexo= rs.getString("sexo");
                boolean operado = rs.getBoolean("operado");
                boolean chip = rs.getBoolean("chip");
                
                tm.addRow(new Object[]{id,nombre,edad,raza,sexo,operado,chip});
            }
            tblPerritos.setModel(tm);
        } catch (SQLException ex) {
            Logger.getLogger(Tablas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.ButtonGroup btnGroupSexo;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JCheckBox chbChip;
    private javax.swing.JCheckBox chbOperado;
    private javax.swing.JComboBox<String> cmbRaza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdbHembra;
    private javax.swing.JRadioButton rdbMacho;
    private javax.swing.JTable tblPerritos;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtIdentificador;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
