/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clase3;

/**
 *
 * @author mjara
 */
public class Checks extends javax.swing.JFrame {

    /**
     * Creates new form Checks
     */
    public Checks() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupSexo = new javax.swing.ButtonGroup();
        chbAqui = new javax.swing.JCheckBox();
        txtCaja1 = new javax.swing.JTextField();
        btnCheck = new javax.swing.JButton();
        chbSet = new javax.swing.JCheckBox();
        btnCheck1 = new javax.swing.JButton();
        btnCheck2 = new javax.swing.JButton();
        txtCaja2 = new javax.swing.JTextField();
        chbState1 = new javax.swing.JCheckBox();
        chbState2 = new javax.swing.JCheckBox();
        chbState3 = new javax.swing.JCheckBox();
        rdbMasculino = new javax.swing.JRadioButton();
        rdbFemenino = new javax.swing.JRadioButton();
        rdbOtro = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        chbAqui.setText("check aqui");

        btnCheck.setText("check");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        chbSet.setText("check");
        chbSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbSetActionPerformed(evt);
            }
        });

        btnCheck1.setText("check");
        btnCheck1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheck1ActionPerformed(evt);
            }
        });

        btnCheck2.setText("un-check");
        btnCheck2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheck2ActionPerformed(evt);
            }
        });

        chbState1.setText("check 1");
        chbState1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chbState1ItemStateChanged(evt);
            }
        });

        chbState2.setText("check 2");
        chbState2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chbState2ItemStateChanged(evt);
            }
        });

        chbState3.setText("check 3");
        chbState3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chbState3ItemStateChanged(evt);
            }
        });

        btnGroupSexo.add(rdbMasculino);
        rdbMasculino.setText("Masculino");

        btnGroupSexo.add(rdbFemenino);
        rdbFemenino.setText("Femenino");

        btnGroupSexo.add(rdbOtro);
        rdbOtro.setText("No quiero especificar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chbSet)
                                .addGap(18, 18, 18)
                                .addComponent(btnCheck1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCheck2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chbAqui)
                                .addGap(18, 18, 18)
                                .addComponent(txtCaja1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCheck))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(txtCaja2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rdbMasculino)
                            .addComponent(chbState1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chbState2)
                                .addGap(18, 18, 18)
                                .addComponent(chbState3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdbFemenino)
                                .addGap(18, 18, 18)
                                .addComponent(rdbOtro)))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbAqui)
                    .addComponent(txtCaja1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCheck))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbSet)
                    .addComponent(btnCheck1)
                    .addComponent(btnCheck2))
                .addGap(57, 57, 57)
                .addComponent(txtCaja2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbState1)
                    .addComponent(chbState2)
                    .addComponent(chbState3))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbMasculino)
                    .addComponent(rdbFemenino)
                    .addComponent(rdbOtro))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        if (chbAqui.isSelected() == true) {
            txtCaja1.setText("el check esta presionado");
        }else{
            txtCaja1.setText("el check no esta presionado");
        }
    }//GEN-LAST:event_btnCheckActionPerformed

    private void btnCheck1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheck1ActionPerformed
        chbSet.setSelected(true);
    }//GEN-LAST:event_btnCheck1ActionPerformed

    private void btnCheck2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheck2ActionPerformed
        chbSet.setSelected(false);
    }//GEN-LAST:event_btnCheck2ActionPerformed

    private void chbSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbSetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbSetActionPerformed

    private void chbState1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chbState1ItemStateChanged
        rellenar();
    }//GEN-LAST:event_chbState1ItemStateChanged

    private void chbState2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chbState2ItemStateChanged
        rellenar();
    }//GEN-LAST:event_chbState2ItemStateChanged

    private void chbState3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chbState3ItemStateChanged
        rellenar();
    }//GEN-LAST:event_chbState3ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Checks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Checks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Checks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Checks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Checks().setVisible(true);
            }
        });
    }
    
    public void rellenar(){
        String palabra = "";
        if (chbState1.isSelected()) {
           palabra += "mi tio ";
        }
        if (chbState2.isSelected()) {
            palabra += "me quiere ";
        }
        if (chbState3.isSelected()) {
            palabra += "mucho!";
        }
        txtCaja2.setText(palabra);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnCheck1;
    private javax.swing.JButton btnCheck2;
    private javax.swing.ButtonGroup btnGroupSexo;
    private javax.swing.JCheckBox chbAqui;
    private javax.swing.JCheckBox chbSet;
    private javax.swing.JCheckBox chbState1;
    private javax.swing.JCheckBox chbState2;
    private javax.swing.JCheckBox chbState3;
    private javax.swing.JRadioButton rdbFemenino;
    private javax.swing.JRadioButton rdbMasculino;
    private javax.swing.JRadioButton rdbOtro;
    private javax.swing.JTextField txtCaja1;
    private javax.swing.JTextField txtCaja2;
    // End of variables declaration//GEN-END:variables
}
